define(_AC_LATEX_PACKAGES_REQUIRE_INTERNE,[
	ifelse($#,0,[],$#,1,[
		AC_LATEX_PACKAGE_REQUIRE($1)
	],[
		AC_LATEX_PACKAGE_REQUIRE($1)
		_AC_LATEX_PACKAGES_REQUIRE_INTERNE(m4_shift($@))
	])
])

AC_DEFUN([AC_LATEX_PACKAGES_REQUIRE],[
	_AC_LATEX_PACKAGES_REQUIRE_INTERNE($1)
])
