package app.common.net;

import java.io.Serializable;

public enum ActionRequest implements Serializable
{
	LOGIN,
	LOGOUT,
	BROWSE_STRATEGY,
	VIEW_STRATEGY,
	RUN_STRATEGY,
	ADD_STRATEGY,
	DELETE_STRATEGY,
	DOWNLOAD_STRATEGY,
	BROWSE_REPORT,
	VIEW_REPORT,
	DELETE_REPORT,
	BROWSE_MARKET,
	BROWSE_DATA_SOURCE,
	CHANGE_DATA_SOURCE,
	BROWSE_USERS,
	ADD_USER,
	DELETE_USER,
	DELETE_DATA,
	CONFIG_MARKET
}
